// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjx2tLotnYRutDuPbRsADY1_irmBBXzw',
    appId: '1:250932802794:android:a575c53c79f8d96bc91393',
    messagingSenderId: '250932802794',
    projectId: 'adventureapp-4d766',
    storageBucket: 'adventureapp-4d766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexmvNTTu4Jzz7Q6R1ZOE7BkjM9iO_FNo',
    appId: '1:250932802794:ios:2f723546f912b507c91393',
    messagingSenderId: '250932802794',
    projectId: 'adventureapp-4d766',
    storageBucket: 'adventureapp-4d766.firebasestorage.app',
    iosBundleId: 'com.adventure.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexmvNTTu4Jzz7Q6R1ZOE7BkjM9iO_FNo',
    appId: '1:250932802794:ios:a00d1c7866cc9841c91393',
    messagingSenderId: '250932802794',
    projectId: 'adventureapp-4d766',
    storageBucket: 'adventureapp-4d766.firebasestorage.app',
    iosBundleId: 'com.example.adventureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZmmSbilvZi2L8qV0zFmUc_G6fFYlBfh8',
    appId: '1:250932802794:web:a39ab5da9912c795c91393',
    messagingSenderId: '250932802794',
    projectId: 'adventureapp-4d766',
    authDomain: 'adventureapp-4d766.firebaseapp.com',
    storageBucket: 'adventureapp-4d766.firebasestorage.app',
  );
}
